name: Node.js CI

on:
  pull_request:

env:
  CI: true
  realm: ${{secrets.realm}}
  base_url: ${{secrets.base_url}}
  consumer_key: ${{secrets.consumer_key}}
  consumer_secret_key: ${{secrets.consumer_secret_key}}
  token: ${{secrets.token}}
  token_secret: ${{secrets.token_secret}}

jobs:
  test:
    name: Node 24
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Set Node.js version
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm build

      - name: Run coverage
        run: pnpm coverage
